"""add_total_resource_slots_to_sgroup

Revision ID: 252a0740ad38
Revises: 3f1dafab60b2
Create Date: 2019-10-01 13:21:41.134247

"""
import textwrap
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '252a0740ad38'
down_revision = '3f1dafab60b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column(
        'scaling_groups',
        sa.Column('total_resource_slots',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=True)
    )

    print('\nSet scaling group\'s total_resource_slots with empty dictionary.')
    query = textwrap.dedent('''\
        UPDATE scaling_groups SET total_resource_slots = '{}'::jsonb;
    ''')
    connection = op.get_bind()
    connection.execute(query)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scaling_groups', 'total_resource_slots')
    # ### end Alembic commands ###
