"""add_total_resource_slots_to_sgroups

Revision ID: 252a0740ad38
Revises: 3f1dafab60b2
Create Date: 2019-10-01 13:21:41.134247

"""
import textwrap
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '252a0740ad38'
down_revision = '3f1dafab60b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column(
        'sgroups_for_domains',
        sa.Column('sg_resource_limits',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=True)
    )
    op.add_column(
        'sgroups_for_groups',
        sa.Column('sg_resource_limits',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=True)
    )
    op.add_column(
        'sgroups_for_keypairs',
        sa.Column('sg_resource_limits',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=True)
    )

    print('\nSet sgroups_for_domain\'s total_resource_slots with empty dictionary.')
    query1 = textwrap.dedent('''\
        UPDATE sgroups_for_domains SET sg_resource_limits = '{}'::jsonb;
    ''')
    query2 = textwrap.dedent('''\
        UPDATE sgroups_for_groups SET sg_resource_limits = '{}'::jsonb;
    ''')
    query3 = textwrap.dedent('''\
        UPDATE sgroups_for_keypairs SET sg_resource_limits = '{}'::jsonb;
    ''')
    connection = op.get_bind()
    connection.execute(query1)
    connection.execute(query2)
    connection.execute(query3)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_column('sgroups_for_domains', 'sg_resource_limits')
    op.drop_column('sgroups_for_groups', 'sg_resource_limits')
    op.drop_column('sgroups_for_keypairs', 'sg_resource_limits')
